### ISSUE TITLE
unable to install on debian10, error is as follows,

### ISSUE THREAD

**Issue by gzcwnk** [zigpy/zigpy-znp#159]
root@e6430-003:~# pip install zigpy-znp
Collecting zigpy-znp
  Using cached https://files.pythonhosted.org/packages/e9/41/0f2c1eaad257785c32dbe71dae0792bf0c7cc8ed5f6b9262f29eb2379ec6/zigpy-znp-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-UWSD2n/zigpy-znp/setup.py", line 7, in <module>
        import zigpy_znp
      File "zigpy_znp/__init__.py", line 5
        __short_version__ = f"{MAJOR_VERSION}.{MINOR_VERSION}"
                                                             ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-UWSD2n/zigpy-znp/
root@e6430-003:~#

**Comment by puddly** [comment]
I see a few problems:

1. zigpy-znp is on version 0.8.1 while your traceback shows a cached `0.3.0` being installed.
2. Python's `f`-strings have been supported since Python 3.3, released in 2012. You seem to be using an earlier Python version. Zigpy only supports Python 3.8 or newer.

With a supported configuration, everything installs properly.
