### ISSUE TITLE
README - Purpose of this library compared to zigpy-cc

### ISSUE THREAD

**Issue by MarhyCZ** [zigpy/zigpy-znp#33]
Hi, 
this is probably really dumb question. However, may I ask what is your goal in functionality or what are the differences against the zigpy-cc library, which is natively bundled with Home Assistant? :) 
And maybe include that explanation in the default readme, so that user can find out if its right for him.

Have a nice day!

**Comment by puddly** [comment]
The goals are the same but the implementations are different:

 - zigpy-cc is a translation of Zigbee2MQTT's [zigbee-herdsman](https://github.com/Koenkk/zigbee-herdsman) library into Python. It isn't actively developed at the moment and there are a few outstanding bugs that are quite difficult for others to fix due to the codebase not being written in traditional Python.

 - zigpy-znp is actively developed and contains bugfixes for the outstanding bugs in zigpy-cc related to profiles/endpoints, channel selection during network formation, and route discovery. zigpy-znp is included in the current Home Assistant beta as the default library for new networks for coordinators running Z-Stack 3, as this is the only version that I've implemented support for at the moment.

Support for Z-Stack Home 1.2 will be ready whenever my replacement CC2531 arrives and zigpy-znp will hopefully be ready as a drop-in replacement for zigpy-cc in the next couple of weeks for the next HA beta.
